In [6]:
import pandas as pd
pd.set_option('display.max_columns', None)
df=pd.read_parquet(r"C:\\Users\\hp\\OneDrive\\Bureau\\personal_projects\\flight-delay-predictor\\data\\processed\\flights_features.parquet")
df.head(10)

,MONTH,DAY_OF_WEEK,DEP_TIME_BLK,DISTANCE_GROUP,CARRIER_NAME,DEPARTING_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND,carrier_avg_delay,airport_avg_delay,day_avg_delay,timeblock_avg_delay,DEP_DEL15
0,7,7,1500-1559,3,American Airlines Inc.,Douglas Municipal,0.00,0.0,0.0,95.0,4.25,0.221606,0.267019,0.215582,0.255949,0
1,4,1,1300-1359,4,SkyWest Airlines Inc.,Stapleton International,0.00,0.0,0.0,71.0,11.41,0.210516,0.272717,0.224000,0.223272,0
2,11,4,0001-0559,2,American Eagle Airlines Inc.,Adams Field,0.00,0.0,0.0,54.0,0.45,0.218666,0.164760,0.231380,0.085002,0
3,3,2,1500-1559,7,Southwest Airlines Co.,San Diego International Lindbergh Fl,0.00,0.0,0.0,64.0,8.05,0.235192,0.189499,0.200430,0.255949,0
4,7,3,0800-0859,1,American Eagle Airlines Inc.,Chicago O'Hare International,0.01,0.0,0.0,94.0,10.51,0.218666,0.276086,0.205753,0.143205,0
5,9,4,0800-0859,2,JetBlue Airways,Ronald Reagan Washington National,0.01,0.0,0.0,89.0,3.80,0.266341,0.203108,0.231380,0.143205,0
6,11,3,0700-0759,8,American Airlines Inc.,Tampa International,0.00,0.0,0.0,69.0,11.18,0.221606,0.191958,0.205753,0.112413,0
7,8,6,1900-1959,3,United Air Lines Inc.,Stapleton International,0.00,0.0,0.0,84.0,8.95,0.216168,0.272717,0.190404,0.303973,1
8,7,3,0800-0859,11,United Air Lines Inc.,Los Angeles International,0.00,0.0,0.0,72.0,8.05,0.216168,0.209998,0.205753,0.143205,0
9,7,2,2000-2059,1,American Airlines Inc.,Pittsburgh International,0.68,0.0,0.0,89.0,8.95,0.221606,0.163054,0.200430,0.312154,1

In [3]:
df.columns.tolist()

['MONTH',
 'DAY_OF_WEEK',
 'DEP_TIME_BLK',
 'DISTANCE_GROUP',
 'CARRIER_NAME',
 'DEPARTING_AIRPORT',
 'PRCP',
 'SNOW',
 'SNWD',
 'TMAX',
 'AWND',
 'carrier_avg_delay',
 'airport_avg_delay',
 'day_avg_delay',
 'timeblock_avg_delay',
 'DEP_DEL15']

In [6]:
df.shape

(3470245, 16)

In [10]:
df_1 = df[df["DEPARTING_AIRPORT"].str.contains("Atlanta Municipal", case=False, na=False)]

df_1.head()

,MONTH,DAY_OF_WEEK,DEP_TIME_BLK,DISTANCE_GROUP,CARRIER_NAME,DEPARTING_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND,carrier_avg_delay,airport_avg_delay,day_avg_delay,timeblock_avg_delay,DEP_DEL15
36,7,1,1500-1559,2,SkyWest Airlines Inc.,Atlanta Municipal,0.0,0.0,0.0,91.0,3.36,0.210516,0.250991,0.224000,0.255949,0
66,2,6,1800-1859,2,SkyWest Airlines Inc.,Atlanta Municipal,0.0,0.0,0.0,54.0,10.51,0.210516,0.250991,0.190404,0.293368,0
79,6,1,1100-1159,4,Delta Air Lines Inc.,Atlanta Municipal,0.0,0.0,0.0,90.0,5.37,0.172528,0.250991,0.224000,0.192654,0
91,5,2,2300-2359,1,SkyWest Airlines Inc.,Atlanta Municipal,0.0,0.0,0.0,84.0,5.14,0.210516,0.250991,0.200430,0.226432,0
130,1,1,1000-1059,2,SkyWest Airlines Inc.,Atlanta Municipal,0.0,0.0,0.0,59.0,6.26,0.210516,0.250991,0.224000,0.178089,0